### ISSUE TITLE
Exception "protocolVersionMismatch"

### ISSUE THREAD

**Issue by luto65** [nlplab/brat#1010]
Dear All,
I've just downloaded v1.3_Crunchy_Frog and installed on cygwin.
python standalone.py &
I connect with chrome to http://localhost:8001/ and it properly redirects to index.xhtml
that however shows only the top bar with the right-left arrows and the brat icon on the top right, and a i in the bottom left.

tools/troubleshooting.sh http://loalhost:8001/  reports
Didn't receive json data when accessing http://localhost:8001/ajax.cgi

I then connect with chrome to http://localhost:8001/ajax.cgi and get the following error
{"exception":["protocolVersionMismatch"],"messages":[["Client-server mismatch, please reload the page to update your client. If this does not work, please contact your administrator\n<br\/>\nClient sent request with version \"None\", server is using version 1","error",-1]]}

Sorry but I am not a JSON expert .. I am using chrome version 27.0.1453.56, 
the python version is 2.6.5; 
I've compiled and installed UJSON but still get the same error message ...

**Comment by mainio29** [comment]
Hi, 
I am also installing this tool in Windows Server 2008 R2. 

However, while following your step:
could you try copying jquery-1.7.1.min.js to jquery.min.js and jquery-ui-1.8.16.custom.min.js to jquery-ui.min.js (all in client/lib).

I couldn't get the file jquery-ui-1.8.16.custom.min.js . 

![capture](https://cloud.githubusercontent.com/assets/25938635/23703345/21eb6714-0408-11e7-867b-8af2bd5155a6.JPG)

Could you guide me in this case. 
Regards, 
Udhyan.

**Comment by Franck-Dernoncourt** [comment]
I tested [luto65's solution above](https://github.com/nlplab/brat/issues/1010#issuecomment-16648278) to run BRAT v1.3 with Cygwin 1.7.22(0.268/5/3) and Python 2.7.3 on Windows 7 SP1 x64 Ultimate, it works great.

**Comment by davidkabiito** [comment]
Hi,
Am trying to install brat on Cygwin 3.0.6(0.338/5/3) and Python 3.7.0 but am getting the errors below;
![image](https://user-images.githubusercontent.com/43681553/56112753-acae8e80-5f64-11e9-8977-50041f824b05.png)

**(
David@FLY-LP822 ~/brat/brat-v1.3_Crunchy_Frog
$ python standalone.py
  File "standalone.py", line 257
    except SystemExit, sts:
                     ^
SyntaxError: invalid syntax

David@FLY-LP822 ~/brat/brat-v1.3_Crunchy_Frog
$ ./tools/troubleshooting.py http://127.0.0.1:8001/
Traceback (most recent call last):
  File "./tools/troubleshooting.py", line 10, in <module>
    from httplib import HTTPConnection, HTTPSConnection
ModuleNotFoundError: No module named 'httplib'**
)

The UI does not also open.

Based on the information here, successful installations have been on Cygwin 1.7.22.
I have been unsuccessful in getting and installing this version of Cygwin. Am kindly requesting for assistance on how to acquire and install this version of Cygwin (Cygwin was requesting me to download a recent version while trying to install the old version).

I prefer to use Cygwin since I want to recruit a team of independent annotators who don't have a reliable internet connection and also want them to do the annotation at any time.
Any suggestions are welcome on how I can install for them Brat to use independently

Thanks
David Kabiito

**Comment by petewahl** [comment]
> Hi,
> Am trying to install brat on Cygwin 3.0.6(0.338/5/3) and Python 3.7.0 but am getting the errors below;
> ![image](https://user-images.githubusercontent.com/43681553/56112753-acae8e80-5f64-11e9-8977-50041f824b05.png)
> 
> **(
> David@FLY-LP822 ~/brat/brat-v1.3_Crunchy_Frog
> $ python standalone.py
> File "standalone.py", line 257
> except SystemExit, sts:
> ^
> SyntaxError: invalid syntax
> 
> David@FLY-LP822 ~/brat/brat-v1.3_Crunchy_Frog
> $ ./tools/troubleshooting.py http://127.0.0.1:8001/
> Traceback (most recent call last):
> File "./tools/troubleshooting.py", line 10, in 
> from httplib import HTTPConnection, HTTPSConnection
> ModuleNotFoundError: No module named 'httplib'**
> )
> 
> The UI does not also open.
> 
> Based on the information here, successful installations have been on Cygwin 1.7.22.
> I have been unsuccessful in getting and installing this version of Cygwin. Am kindly requesting for assistance on how to acquire and install this version of Cygwin (Cygwin was requesting me to download a recent version while trying to install the old version).
> 
> I prefer to use Cygwin since I want to recruit a team of independent annotators who don't have a reliable internet connection and also want them to do the annotation at any time.
> Any suggestions are welcome on how I can install for them Brat to use independently
> 
> Thanks
> David Kabiito

Change your python installation to python2. Don't use a windows build. It does not support os.fork(). Use a cygwin build. Check your cygwin installer for python2 package
