### ISSUE TITLE
Lines indented with space chars cause visualization and annotation issues

### ISSUE THREAD

**Issue by kottmann** [nlplab/brat#1040]
The sentence detection (set to new line) fails for the following to lines:
space_char space_char space_char space_char line1
space_char space_char space_char space_char line2

In my test both lines are displayed in one line. 

If an annotation is created containing line1 and line2 brat prints out this warning:
"WARNING
The fragment [10, 19](line2) is not contained in its designated chunk [14, 19] most likely due to the fragment starting or ending with a space, please verify the sanity of your data since we are unable to visualise this fragment correctly and will drop leading space characters"

Both issues go away if I remove the space chars in the test file, so it looks like this:
line1
line2

**Comment by acovi** [comment]
@kottmann I've run into the same problem as I was using v1.3 - the package download option. I've switched to branch "python2" and now the issue is gone for new annotations.
However, previously annotated documents still are showing the warning messages.
Did you have the same experience? Did you convert previously annotated documents to avoid the messages?
Thanks for your reply.
