### ISSUE TITLE
Does Japanese tokenization using MeCab work with brat?

### ISSUE THREAD

**Issue by sunmoonStern** [nlplab/brat#1155]
Hello, does brat work with MeCab? My tools.conf looks like this and I am using brat for annotation for my own NLP tasks (dealing with Japanese text) for a few months now but I don't think brat is recognizing different words/tokens. MeCab can be used to generate output in several different formats. Could you tell me what kind of output brat is assuming? Thanks in advance.

```
[options]

# Possible values for validate:
Validation	validate:all

# Possible values for tokenizer
Tokens tokenizer:mecab
#Tokens	   tokenizer:whitespace

# Possible values for splitter:
Sentences	splitter:regex

# Possible values for logfile:
Annotation-log logfile:<NONE>

[search]
Google       <URL>:http://www.google.com/search?q=%s
Wikipedia    <URL>:http://en.wikipedia.org/wiki/Special:Search?search=%s

[annotators]

[disambiguators]

[normalization]

```

**Comment by ninjin** [comment]
Please do not use the issue tracker for questions, the issue tracker is for issues, use the mailing list for questions.  Closing.  It was several years since I last looked at the MeCab code and I can not remember the exact format we used, if you send the same question to the mailing list I will try to have a look at it within a few days.
