### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by bethard** [nlplab/brat#1346]
There hasn't been an official release since 2012, but I see that @amadanmath and @spyysalo have been active in the last year. Are there any plans for a new official release?

**Comment by amadanmath** [comment]
I'm doing small fixes here and there, but all of the original developers
have moved to other positions, so an official release might not be likely
(at least from my side). But who knows.
I do encourage people to use the GitHub clone rather than the packaged
release, since there's been many bugfixes and features since 2012.
There may be new bugs as well though, so please report if you find any;
especially in the Python3 conversion.

Goran

**Comment by icedwater** [comment]
Found this link when looking for a Python3 port. I'll test it, thanks :)

**Comment by amadanmath** [comment]
It should be, but there may be errors or unconverted files, particularly in `tools`. If anyone finds any such, yell.
